development:
  adapter: postgresql
  encoding: unicode
  database: arlo_development
  pool: 5
  username: tguibord
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: arlo_test
  pool: 5
  username: tguibord
  password:
